### ISSUE TITLE
bicep deployment config issues

### ISSUE THREAD

**Issue by cajetzer** [microsoft/Damu#67]
## RBAC roles missing:
- function needs the below on resource group
![image](https://github.com/user-attachments/assets/c0b698d6-5d12-437a-bfa4-aabcdc8ab4fa)
- search service needs: AZURE AI DEVELOPER on resource group

## web app environment variable updates, need to use environment given in deployment name as prefix
- AISearchOptions__IndexName
- AISearchOptions__SemanticConfigurationName

```[tasklist]
### Tasks
- [x] Cognitive Services OpenAI User
- [x] Storage Blob Data Contributor
- [x] Search Index Data Reader
- [x] Cognitive Services User
- [x] Search Index Data Contributor
- [x] Azure AI Developer
- [ ] Search Service Contributor
```
